import type { BusinessProfile, Purchase, Supplier } from "@/types";
import { asNumber, printCurrency, printDate, printGSTIN, printQty } from "../printUtils";
import { PrintAuthorizedSignature, PrintBusinessIdentity } from "./PrintBranding";

export function PurchaseBillTemplate({ purchase, business }: { purchase: Purchase; business: BusinessProfile }) {
  const supplier = typeof purchase.supplier === "object" ? purchase.supplier as Supplier : undefined;
  return <article className="print-area print-a4 bg-white p-8 text-slate-900" style={{ width: "186mm", minHeight: "270mm", backgroundColor: "#ffffff", color: "#0f172a", colorScheme: "light" }}>
    <header className="flex justify-between border-b-2 border-indigo-600 pb-5"><PrintBusinessIdentity business={business} /><div className="text-right"><div className="rounded bg-indigo-600 px-3 py-1 text-xs font-bold text-white">PURCHASE BILL</div><p className="mt-3 font-bold">#{purchase.purchaseNumber}</p><p className="text-xs text-slate-500">{printDate(purchase.purchaseDate)}</p></div></header>
    <section className="my-6 grid grid-cols-2 gap-6 rounded-lg bg-slate-50 p-4 text-sm"><div><p className="text-[10px] font-bold uppercase tracking-widest text-slate-400">Supplier</p><p className="font-bold">{purchase.supplierName}</p>{supplier?.phone && <p>{supplier.phone}</p>}{supplier?.address && <p>{supplier.address}</p>}{supplier?.gstNumber && <p>GSTIN: {printGSTIN(supplier.gstNumber)}</p>}</div><div><p className="text-[10px] font-bold uppercase tracking-widest text-slate-400">Bill Details</p><p>Supplier Invoice: <strong>{purchase.invoiceNumber || "-"}</strong></p><p>State of Supply: <strong>{purchase.stateOfSupply || "-"}</strong></p><p>Status: <strong className="uppercase">{purchase.paymentStatus}</strong></p></div></section>
    <table className="w-full border-collapse text-xs"><thead><tr className="bg-indigo-600 text-white"><th className="p-2 text-left">#</th><th className="p-2 text-left">Product / SKU</th><th className="p-2 text-right">Qty</th><th className="p-2 text-right">Cost</th><th className="p-2 text-right">Sale Price</th><th className="p-2 text-right">Tax</th><th className="p-2 text-right">Amount</th></tr></thead><tbody>{purchase.items.map((item, i) => <tr key={`${item.sku}-${i}`} className="border-b border-slate-200"><td className="p-2">{i + 1}</td><td className="p-2"><p className="font-semibold">{item.name}</p><p className="text-slate-500">{item.sku}</p></td><td className="p-2 text-right">{printQty(item.quantity)}</td><td className="p-2 text-right">{printCurrency(item.purchasePrice)}</td><td className="p-2 text-right">{printCurrency(item.salesPrice)}</td><td className="p-2 text-right">{item.taxRate || 0}%</td><td className="p-2 text-right font-semibold">{printCurrency(item.total)}</td></tr>)}</tbody></table>
    <section className="avoid-break mt-6 ml-auto w-[80mm] space-y-2 text-sm"><div className="flex justify-between"><span>Subtotal</span><span>{printCurrency(purchase.subtotal)}</span></div>{asNumber(purchase.discountAmount) > 0 && <div className="flex justify-between text-rose-600"><span>Discount</span><span>-{printCurrency(purchase.discountAmount)}</span></div>}<div className="flex justify-between"><span>Tax</span><span>{printCurrency(purchase.taxAmount)}</span></div>{asNumber(purchase.shippingCharges) > 0 && <div className="flex justify-between"><span>Shipping / Charges</span><span>{printCurrency(purchase.shippingCharges)}</span></div>}<div className="flex justify-between rounded bg-indigo-600 p-3 text-base font-bold text-white"><span>Grand Total</span><span>{printCurrency(purchase.totalAmount)}</span></div><div className="flex justify-between"><span>Paid</span><span>{printCurrency(purchase.amountPaid)}</span></div><div className="flex justify-between font-semibold"><span>Due</span><span>{printCurrency(purchase.dueAmount)}</span></div></section>
    <footer className="avoid-break mt-12 flex justify-between border-t pt-5 text-xs"><p className="max-w-[95mm] text-slate-500">{purchase.notes || "This document records goods purchased and received as stated above."}</p><PrintAuthorizedSignature business={business} /></footer>
  </article>;
}
