import type { BusinessProfile, SaleReturn } from "@/types";
import { asNumber, printCurrency, printDate, printGSTIN, printQty } from "../printUtils";
import { PrintAuthorizedSignature, PrintBusinessIdentity } from "./PrintBranding";

export function SaleReturnTemplate({ note, business }: { note: SaleReturn; business: BusinessProfile }) {
  return <article className="print-area print-a4 bg-white p-8 text-slate-900" style={{ width: "186mm", minHeight: "270mm", backgroundColor: "#ffffff", color: "#0f172a", colorScheme: "light" }}>
    <header className="flex justify-between border-b-2 border-indigo-600 pb-5"><PrintBusinessIdentity business={business} /><div className="text-right"><div className="rounded bg-indigo-600 px-3 py-1 text-xs font-bold text-white">CREDIT NOTE</div><p className="mt-3 font-bold">#{note.creditNoteNo}</p><p className="text-xs text-slate-500">{printDate(note.returnDate)}</p></div></header>
    <section className="my-6 grid grid-cols-2 gap-6 rounded-lg bg-slate-50 p-4 text-sm"><div><p className="text-[10px] font-bold uppercase tracking-widest text-slate-400">Customer Details</p><p className="font-bold">{note.customerName}</p>{note.customerPhone && <p>{note.customerPhone}</p>}{note.billingAddress && <p>{note.billingAddress}</p>}{note.customerGstNo && <p>GSTIN: {printGSTIN(note.customerGstNo)}</p>}</div><div><p className="text-[10px] font-bold uppercase tracking-widest text-slate-400">Reference</p><p>Original Invoice: <strong>{note.invoiceNumber}</strong></p><p>State of Supply: <strong>{note.stateOfSupply || "-"}</strong></p><p>Settlement: <strong className="uppercase">{note.refundType.replaceAll("_", " ")}</strong></p></div></section>
    <table className="w-full border-collapse text-xs"><thead><tr className="bg-indigo-600 text-white"><th className="p-2 text-left">#</th><th className="p-2 text-left">Returned Item / Reason</th><th className="p-2 text-right">Qty</th><th className="p-2 text-right">Rate</th><th className="p-2 text-right">Tax</th><th className="p-2 text-right">Credit</th></tr></thead><tbody>{note.items.map((item, i) => <tr key={`${item.itemName}-${i}`} className="border-b border-slate-200"><td className="p-2">{i + 1}</td><td className="p-2"><p className="font-semibold">{item.itemName}</p><p className="text-slate-500">{item.reason}</p></td><td className="p-2 text-right">{printQty(item.returnQty)}</td><td className="p-2 text-right">{printCurrency(item.pricePerUnit)}</td><td className="p-2 text-right">{item.taxPercent}%</td><td className="p-2 text-right font-semibold">{printCurrency(item.returnAmount)}</td></tr>)}</tbody></table>
    <section className="avoid-break mt-6 ml-auto w-[82mm] space-y-2 text-sm"><div className="flex justify-between"><span>Subtotal</span><span>{printCurrency(note.subtotal)}</span></div>{asNumber(note.totalDiscount) > 0 && <div className="flex justify-between text-emerald-700"><span>Discount Reversed</span><span>-{printCurrency(note.totalDiscount)}</span></div>}<div className="flex justify-between"><span>Tax Reversed</span><span>{printCurrency(note.totalTax)}</span></div><div className="flex justify-between rounded bg-indigo-600 p-3 text-base font-bold text-white"><span>Total Credit</span><span>{printCurrency(note.grandTotal)}</span></div><div className="flex justify-between"><span>Refunded</span><span>{printCurrency(note.refundedAmount)}</span></div><div className="flex justify-between font-semibold"><span>Credit Balance</span><span>{printCurrency(note.creditBalance)}</span></div></section>
    <footer className="avoid-break mt-12 flex justify-between border-t pt-5 text-xs"><p className="max-w-[95mm] text-slate-500">{note.notes || "Credit issued against goods returned as detailed above."}</p><PrintAuthorizedSignature business={business} /></footer>
  </article>;
}
